// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2_0Dx6ecjTSVoIyZ7yrbR1lC3rXIUHZ0',
    appId: '1:47179927094:web:5799cb94a912731dab9297',
    messagingSenderId: '47179927094',
    projectId: 'lomba-b1608',
    authDomain: 'lomba-b1608.firebaseapp.com',
    storageBucket: 'lomba-b1608.firebasestorage.app',
    measurementId: 'G-P6W47EWVX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHOHXI56OWYeGbX2dVe66lqW0yTdAzfy4',
    appId: '1:47179927094:android:c5486cc357bd193aab9297',
    messagingSenderId: '47179927094',
    projectId: 'lomba-b1608',
    storageBucket: 'lomba-b1608.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi4vy68GWrkuyBYg56F8xcgv_G7efm33E',
    appId: '1:47179927094:ios:62f1a21b7d6f1934ab9297',
    messagingSenderId: '47179927094',
    projectId: 'lomba-b1608',
    storageBucket: 'lomba-b1608.firebasestorage.app',
    iosBundleId: 'com.example.cybernusa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi4vy68GWrkuyBYg56F8xcgv_G7efm33E',
    appId: '1:47179927094:ios:62f1a21b7d6f1934ab9297',
    messagingSenderId: '47179927094',
    projectId: 'lomba-b1608',
    storageBucket: 'lomba-b1608.firebasestorage.app',
    iosBundleId: 'com.example.cybernusa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2_0Dx6ecjTSVoIyZ7yrbR1lC3rXIUHZ0',
    appId: '1:47179927094:web:472d09051ce52600ab9297',
    messagingSenderId: '47179927094',
    projectId: 'lomba-b1608',
    authDomain: 'lomba-b1608.firebaseapp.com',
    storageBucket: 'lomba-b1608.firebasestorage.app',
    measurementId: 'G-NKZS0DFYYQ',
  );
}
